apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/kofia-435616/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URL
        - name: PASS_SEC
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PASS_SEC
        - name: JWT_SEC
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SEC
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: MPESA_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MPESA_CONSUMER_KEY
        - name: MPESA_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MPESA_CONSUMER_SECRET
        - name: MPESA_SHORTCODE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MPESA_SHORTCODE
        - name: MPESA_PASSKEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MPESA_PASSKEY  

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15