apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-health-check
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /api/health
    port: 5000